###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: "3.1"
services:

    mailhog:
      image: mailhog/mailhog:latest
      container_name: env-mailhog
      ports:
        - "8025:8025"

    redis:
      image: redis:alpine
      container_name: env-redis

    mysql:
      image: mysql:8.0
      container_name: env-mysql
      working_dir: /application
      volumes:
        - .:/application
        - /vm_data/jobeet-data:/var/lib/mysql
      environment:
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_DATABASE=test
        - MYSQL_USER=user
        - MYSQL_PASSWORD=user
      ports:
        - "3306:3306"

##    mariadb:
##      image: mariadb:10.4
##      container_name: env-mariadb
##      working_dir: /application
##      volumes:
##        - .:/application
##      environment:
##        - MYSQL_ROOT_PASSWORD=root
##        - MYSQL_DATABASE=sight
##        - MYSQL_USER=user
##        - MYSQL_PASSWORD=user
##      ports:
##        - "3003:3306"

    webserver:
      image: nginx:alpine
      container_name: env-webserver
      working_dir: /application
      volumes:
          - .:/application
          - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "8000:80"

    php-fpm:
      build: phpdocker/php-fpm
      container_name: env-php-fpm
      working_dir: /application
      volumes:
        - .:/application
        - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.4/fpm/conf.d/99-overrides.ini

    node:
      image: node:10.13.0
      container_name: env-node
      working_dir: /application
      volumes:
        - .:/application

