controllers:
    resource: ../../src/Controller/
    type: annotation
    prefix:
        en: ''
        ru: '/ru'

kernel:
    resource: ../../src/Kernel.php
    type: annotation

api_controllers:
    resource: ../../src/Controller/API/
    type: annotation
    prefix: /api/v1/
